import { randomUUID } from "node:crypto";
import type { QueryResultRow } from "pg";
import { z } from "zod";
import { AppError } from "../../lib/errors.js";

export type AccountQuerySource = {
  query<R extends QueryResultRow = QueryResultRow>(
    text: string,
    values?: readonly unknown[],
  ): Promise<{ rows: R[] }>;
};

const settingsAccountSchema = z
  .object({
    id: z.union([z.string().trim().min(1).max(512), z.number().finite()]),
    name: z.string().trim().min(1).max(200),
    currency: z.string().trim().min(1).max(32).optional(),
    currencyCode: z.string().trim().min(1).max(32).optional(),
    size: z.number().finite().nonnegative().nullable().optional(),
    accountSize: z.number().finite().nonnegative().nullable().optional(),
    color: z.string().trim().min(1).max(64).nullable().optional(),
  })
  .passthrough();

const settingsAccountsSchema = z.array(settingsAccountSchema).max(1_000);

export type SettingsAccount = {
  legacyId: string;
  name: string;
  currencyCode: string;
  accountSize: number | null;
  color: string | null;
  metadata: Record<string, unknown>;
};

const currencyAliases: Readonly<Record<string, string>> = {
  "$": "USD",
  "US$": "USD",
  USD: "USD",
  "₹": "INR",
  RS: "INR",
  "RS.": "INR",
  INR: "INR",
  "€": "EUR",
  EUR: "EUR",
  "£": "GBP",
  GBP: "GBP",
};

function normalizeCurrency(value: string | undefined): string {
  const normalized = value?.trim().toUpperCase() || "USD";
  const currencyCode = currencyAliases[normalized] ?? normalized;
  if (!/^[A-Z]{3}$/.test(currencyCode)) {
    throw new AppError(400, "SETTINGS_ACCOUNT_INVALID", `Unsupported account currency: ${value}`);
  }
  return currencyCode;
}

/**
 * Parses the user-facing account array kept in settings. The legacy account ID
 * is the browser's stable public identifier; the database UUID remains private
 * and is deliberately not regenerated by account edits or archive/revive.
 */
export function normalizeSettingsAccounts(settings: Record<string, unknown>): SettingsAccount[] {
  const value = settings.accounts ?? [];
  const parsed = settingsAccountsSchema.safeParse(value);
  if (!parsed.success) {
    throw new AppError(400, "SETTINGS_ACCOUNT_INVALID", "Settings contain an invalid account list");
  }
  const seen = new Set<string>();
  return parsed.data.map((account) => {
    const legacyId = String(account.id).trim();
    if (seen.has(legacyId)) {
      throw new AppError(400, "SETTINGS_ACCOUNT_INVALID", `Duplicate account ID: ${legacyId}`);
    }
    seen.add(legacyId);
    return {
      legacyId,
      name: account.name,
      currencyCode: normalizeCurrency(account.currencyCode ?? account.currency),
      accountSize: account.accountSize ?? account.size ?? null,
      color: account.color ?? null,
      metadata: account,
    };
  });
}

/**
 * Mirrors settings.accounts into the normalized relational account table in
 * the caller's settings transaction. Removed accounts are archived so their
 * UUIDs, historical trades, and later re-addition remain stable.
 */
export async function syncAccountsFromSettings(
  source: AccountQuerySource,
  userId: string,
  settings: Record<string, unknown>,
): Promise<Map<string, string>> {
  const accounts = normalizeSettingsAccounts(settings);
  const resolved = new Map<string, string>();
  for (const account of accounts) {
    const result = await source.query<{ id: string }>(
      `INSERT INTO accounts (
         id, user_id, legacy_account_id, name, currency_code,
         account_size, color, metadata, archived_at
       ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,NULL)
       ON CONFLICT (user_id, legacy_account_id) DO UPDATE SET
         name=EXCLUDED.name,
         currency_code=EXCLUDED.currency_code,
         account_size=EXCLUDED.account_size,
         color=EXCLUDED.color,
         metadata=accounts.metadata || EXCLUDED.metadata,
         archived_at=NULL
       RETURNING id`,
      [
        randomUUID(),
        userId,
        account.legacyId,
        account.name,
        account.currencyCode,
        account.accountSize,
        account.color,
        JSON.stringify({ managedBy: "user_settings", settings: account.metadata }),
      ],
    );
    const row = result.rows[0];
    if (!row) throw new Error("Failed to normalize an Edgebook account");
    resolved.set(account.legacyId, row.id);
  }

  const archived = await source.query<{ id: string }>(
    `UPDATE accounts SET archived_at=COALESCE(archived_at, now())
     WHERE user_id=$1
       AND legacy_account_id IS NOT NULL
       AND metadata->>'managedBy'='user_settings'
       AND NOT (legacy_account_id = ANY($2::text[]))
     RETURNING id`,
    [userId, accounts.map((account) => account.legacyId)],
  );
  if (archived.rows.length > 0) {
    await source.query(
      `UPDATE broker_connections SET
         mapped_account_id=NULL,
         legacy_mapped_account_id=NULL
       WHERE user_id=$1 AND mapped_account_id = ANY($2::uuid[])`,
      [userId, archived.rows.map((account) => account.id)],
    );
  }
  return resolved;
}

export async function resolveOwnedAccountMapping(
  source: AccountQuerySource,
  userId: string,
  publicId: string | null,
): Promise<{ internalId: string | null; legacyId: string | null }> {
  if (publicId === null) return { internalId: null, legacyId: null };
  const result = await source.query<{ id: string; legacy_account_id: string | null }>(
    `SELECT id, legacy_account_id FROM accounts
     WHERE user_id=$1 AND archived_at IS NULL
       AND (id::text=$2 OR legacy_account_id=$2)
     LIMIT 1`,
    [userId, publicId],
  );
  const account = result.rows[0];
  if (!account) throw new AppError(400, "ACCOUNT_MAPPING_INVALID", "The selected Edgebook account does not exist");
  return { internalId: account.id, legacyId: account.legacy_account_id ?? publicId };
}
