-- Edgebook PostgreSQL foundation.
-- UUID values are generated by the Node application so this migration has no
-- extension dependency and works on managed or self-hosted PostgreSQL.

CREATE TABLE users (
  id uuid PRIMARY KEY,
  legacy_firebase_uid text UNIQUE,
  -- Nullable during the Firebase import. The importer should populate the
  -- immutable Google provider UID wherever available before auth cutover.
  google_sub text UNIQUE,
  email text NOT NULL,
  email_verified boolean NOT NULL DEFAULT false,
  display_name text,
  avatar_url text,
  legacy_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  disabled_at timestamptz,
  CHECK (google_sub IS NULL OR length(google_sub) BETWEEN 1 AND 255),
  CHECK (length(email) BETWEEN 3 AND 320)
);

CREATE TABLE sessions (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash bytea NOT NULL UNIQUE,
  csrf_hash bytea NOT NULL,
  user_agent text,
  ip_address inet,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  idle_expires_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  CHECK (idle_expires_at <= expires_at)
);

CREATE INDEX sessions_user_active_idx
  ON sessions (user_id, expires_at DESC)
  WHERE revoked_at IS NULL;

CREATE TABLE oauth_transactions (
  id uuid PRIMARY KEY,
  user_id uuid REFERENCES users(id) ON DELETE CASCADE,
  session_id uuid REFERENCES sessions(id) ON DELETE CASCADE,
  provider text NOT NULL,
  state_hash bytea NOT NULL UNIQUE,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_settings (
  user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  legacy_firebase_path text,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (version >= 0)
);

CREATE TABLE accounts (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  legacy_account_id text,
  name text NOT NULL,
  currency_code text NOT NULL DEFAULT 'USD',
  account_size numeric(30, 8),
  color text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  archived_at timestamptz,
  UNIQUE (user_id, legacy_account_id),
  CHECK (currency_code ~ '^[A-Z]{3}$')
);

CREATE TABLE broker_connections (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  legacy_firebase_doc_id text,
  provider text NOT NULL,
  external_account_id text,
  account_label text,
  mapped_account_id uuid REFERENCES accounts(id) ON DELETE SET NULL,
  connected boolean NOT NULL DEFAULT false,
  access_token_ciphertext text,
  refresh_token_ciphertext text,
  encryption_key_version integer,
  token_expires_at timestamptz,
  sync_cursor jsonb NOT NULL DEFAULT '{}'::jsonb,
  provider_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  legacy_document jsonb NOT NULL DEFAULT '{}'::jsonb,
  connected_at timestamptz,
  last_sync_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, legacy_firebase_doc_id)
);

CREATE UNIQUE INDEX broker_connections_external_unique_idx
  ON broker_connections (user_id, provider, external_account_id)
  WHERE external_account_id IS NOT NULL;

CREATE INDEX broker_connections_scheduler_idx
  ON broker_connections (provider, connected, last_sync_at)
  WHERE connected = true;

CREATE TABLE trades (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  legacy_firebase_doc_id text,
  account_id uuid REFERENCES accounts(id) ON DELETE SET NULL,
  legacy_account_id text,
  broker_connection_id uuid REFERENCES broker_connections(id) ON DELETE SET NULL,
  -- source_system answers "whose data is this?"; ingestion_method answers
  -- "how did it arrive?" (manual, api, csv, migration, webhook).
  source_system text NOT NULL DEFAULT 'manual',
  ingestion_method text NOT NULL DEFAULT 'manual',
  external_trade_key text,
  broker_trade_id text,
  symbol text NOT NULL,
  asset text,
  instrument text,
  option_type text,
  strike numeric(30, 10),
  expiry date,
  exchange text,
  product text,
  direction text NOT NULL,
  entry_price numeric(30, 10) NOT NULL,
  exit_price numeric(30, 10),
  quantity numeric(30, 10) NOT NULL,
  pnl numeric(30, 10),
  stop_loss numeric(30, 10),
  take_profit numeric(30, 10),
  is_open boolean,
  trade_date date NOT NULL,
  entry_at timestamptz,
  exit_at timestamptz,
  legacy_entry_time time,
  legacy_exit_time time,
  strategy text,
  emotion text,
  notes text,
  tags jsonb NOT NULL DEFAULT '[]'::jsonb,
  psychology jsonb NOT NULL DEFAULT '{}'::jsonb,
  custom_fields jsonb NOT NULL DEFAULT '{}'::jsonb,
  broker_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  legacy_document jsonb NOT NULL DEFAULT '{}'::jsonb,
  calculation_version integer NOT NULL DEFAULT 1,
  row_version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CHECK (direction IN ('Long', 'Short')),
  CHECK (quantity >= 0),
  CHECK (calculation_version >= 1),
  CHECK (row_version >= 1)
);

CREATE UNIQUE INDEX trades_legacy_id_unique_idx
  ON trades (user_id, legacy_firebase_doc_id)
  WHERE legacy_firebase_doc_id IS NOT NULL;

CREATE UNIQUE INDEX trades_external_key_unique_idx
  ON trades (broker_connection_id, external_trade_key)
  WHERE broker_connection_id IS NOT NULL AND external_trade_key IS NOT NULL;

CREATE INDEX trades_user_active_date_idx
  ON trades (user_id, trade_date DESC, updated_at DESC)
  WHERE deleted_at IS NULL;

CREATE INDEX trades_user_deleted_idx
  ON trades (user_id, deleted_at DESC)
  WHERE deleted_at IS NOT NULL;

CREATE INDEX trades_user_source_idx
  ON trades (user_id, source_system, ingestion_method, trade_date DESC);

CREATE INDEX trades_legacy_account_idx
  ON trades (user_id, legacy_account_id, trade_date DESC)
  WHERE legacy_account_id IS NOT NULL;

CREATE TABLE trade_executions (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  trade_id uuid REFERENCES trades(id) ON DELETE SET NULL,
  broker_connection_id uuid NOT NULL REFERENCES broker_connections(id) ON DELETE CASCADE,
  external_execution_id text NOT NULL,
  external_position_id text,
  side text NOT NULL,
  quantity numeric(30, 10) NOT NULL,
  price numeric(30, 10) NOT NULL,
  pnl numeric(30, 10),
  commission numeric(30, 10),
  swap numeric(30, 10),
  currency_code text,
  executed_at timestamptz NOT NULL,
  raw_payload jsonb NOT NULL,
  imported_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (broker_connection_id, external_execution_id),
  CHECK (side IN ('BUY', 'SELL')),
  CHECK (quantity > 0)
);

CREATE INDEX trade_executions_position_idx
  ON trade_executions (broker_connection_id, external_position_id, executed_at);

CREATE TABLE broker_orders (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  broker_connection_id uuid REFERENCES broker_connections(id) ON DELETE SET NULL,
  legacy_firebase_doc_id text,
  external_order_id text NOT NULL,
  status text,
  raw_payload jsonb NOT NULL,
  broker_updated_at timestamptz,
  synced_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, legacy_firebase_doc_id),
  UNIQUE (broker_connection_id, external_order_id)
);

CREATE TABLE mood_checkins (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  legacy_id text,
  kind text NOT NULL,
  emotion text NOT NULL,
  confidence smallint,
  notes text,
  occurred_at timestamptz,
  local_date date NOT NULL,
  local_time time,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, legacy_id),
  CHECK (confidence IS NULL OR confidence BETWEEN 1 AND 10)
);

CREATE INDEX mood_checkins_user_date_idx
  ON mood_checkins (user_id, local_date DESC, created_at DESC);

CREATE TABLE daily_journal_entries (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  journal_date date NOT NULL,
  entry jsonb NOT NULL,
  legacy_document jsonb NOT NULL DEFAULT '{}'::jsonb,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, journal_date),
  CHECK (version >= 1)
);

CREATE TABLE notifications (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  legacy_firebase_doc_id text,
  type text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  category text,
  action_label text,
  action_target text,
  is_read boolean NOT NULL DEFAULT false,
  dedupe_key text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, legacy_firebase_doc_id)
);

CREATE UNIQUE INDEX notifications_dedupe_idx
  ON notifications (user_id, dedupe_key)
  WHERE dedupe_key IS NOT NULL;

CREATE INDEX notifications_feed_idx
  ON notifications (user_id, created_at DESC);

CREATE INDEX notifications_unread_idx
  ON notifications (user_id, created_at DESC)
  WHERE is_read = false;

CREATE TABLE pending_duplicates (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  legacy_firebase_doc_id text,
  incoming_trade jsonb NOT NULL,
  existing_trade_id uuid REFERENCES trades(id) ON DELETE SET NULL,
  source text,
  status text NOT NULL DEFAULT 'pending',
  resolution jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  UNIQUE (user_id, legacy_firebase_doc_id),
  CHECK (status IN ('pending', 'resolved', 'dismissed'))
);

CREATE TABLE file_objects (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  trade_id uuid NOT NULL REFERENCES trades(id) ON DELETE CASCADE,
  legacy_storage_url text,
  storage_key text NOT NULL UNIQUE,
  original_name text NOT NULL,
  content_type text NOT NULL,
  byte_size bigint NOT NULL,
  sha256 bytea NOT NULL,
  width integer,
  height integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CHECK (byte_size > 0),
  CHECK (width IS NULL OR width > 0),
  CHECK (height IS NULL OR height > 0)
);

CREATE INDEX file_objects_trade_idx
  ON file_objects (user_id, trade_id, created_at)
  WHERE deleted_at IS NULL;

-- Deleting database metadata never loses the physical storage key. A worker
-- retries failed filesystem cleanup until completed_at is set.
CREATE TABLE file_deletion_queue (
  id bigserial PRIMARY KEY,
  storage_key text NOT NULL UNIQUE,
  attempts integer NOT NULL DEFAULT 0,
  last_error text,
  not_before timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE OR REPLACE FUNCTION enqueue_file_deletion()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO file_deletion_queue (storage_key)
  VALUES (OLD.storage_key)
  ON CONFLICT (storage_key) DO UPDATE SET
    completed_at = NULL,
    not_before = now();
  RETURN OLD;
END;
$$;

CREATE TRIGGER file_objects_enqueue_deletion
  AFTER DELETE ON file_objects
  FOR EACH ROW EXECUTE FUNCTION enqueue_file_deletion();

CREATE TABLE webhook_events (
  id uuid PRIMARY KEY,
  provider text NOT NULL,
  provider_event_key text NOT NULL,
  broker_connection_id uuid REFERENCES broker_connections(id) ON DELETE SET NULL,
  signature_verified boolean NOT NULL,
  payload jsonb NOT NULL,
  status text NOT NULL DEFAULT 'received',
  attempt_count integer NOT NULL DEFAULT 0,
  last_error text,
  received_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz,
  UNIQUE (provider, provider_event_key)
);

CREATE TABLE sync_runs (
  id uuid PRIMARY KEY,
  broker_connection_id uuid NOT NULL REFERENCES broker_connections(id) ON DELETE CASCADE,
  job_key text NOT NULL,
  sync_type text NOT NULL,
  status text NOT NULL,
  cursor_before jsonb,
  cursor_after jsonb,
  counters jsonb NOT NULL DEFAULT '{}'::jsonb,
  error_code text,
  error_message text,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  UNIQUE (broker_connection_id, job_key)
);

CREATE TABLE symbol_specs (
  id uuid PRIMARY KEY,
  provider text NOT NULL,
  provider_environment text NOT NULL DEFAULT 'live',
  external_account_id text,
  external_symbol_id text NOT NULL,
  symbol_name text NOT NULL,
  specification jsonb NOT NULL,
  fetched_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  UNIQUE (provider, provider_environment, external_account_id, external_symbol_id)
);

CREATE TABLE audit_events (
  id bigserial PRIMARY KEY,
  user_id uuid REFERENCES users(id) ON DELETE SET NULL,
  session_id uuid REFERENCES sessions(id) ON DELETE SET NULL,
  event_type text NOT NULL,
  target_type text,
  target_id text,
  ip_address inet,
  user_agent text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_events (
  id bigserial PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  event_type text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX user_events_replay_idx ON user_events (user_id, id);
CREATE INDEX user_events_retention_idx ON user_events (occurred_at);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER settings_set_updated_at BEFORE UPDATE ON user_settings
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER accounts_set_updated_at BEFORE UPDATE ON accounts
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER broker_connections_set_updated_at BEFORE UPDATE ON broker_connections
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trades_set_updated_at BEFORE UPDATE ON trades
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER moods_set_updated_at BEFORE UPDATE ON mood_checkins
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER journals_set_updated_at BEFORE UPDATE ON daily_journal_entries
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER notifications_set_updated_at BEFORE UPDATE ON notifications
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
